{
  "uid" : "33c0d416f156efbb",
  "name" : "Test submenu and button on the Documentation page",
  "fullName" : "Test Redirection of Pages: Test submenu and button on the Documentation page",
  "historyId" : "b4635d60b0cc5c73d971f138ef5fb774",
  "time" : {
    "start" : 1698836812270,
    "stop" : 1698836813202,
    "duration" : 932
  },
  "status" : "broken",
  "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_ADDRESS_UNREACHABLE\n  (Session info: headless chrome=114.0.5735.133)\nStacktrace:\n#0 0x55795fd574e3 <unknown>\n#1 0x55795fa86c76 <unknown>\n#2 0x55795fa7ec7f <unknown>\n#3 0x55795fa70ca2 <unknown>\n#4 0x55795fa72412 <unknown>\n#5 0x55795fa710ca <unknown>\n#6 0x55795fa70168 <unknown>\n#7 0x55795fa6ffa0 <unknown>\n#8 0x55795fa6e9bf <unknown>\n#9 0x55795fa6efed <unknown>\n#10 0x55795fa88b06 <unknown>\n#11 0x55795fafa9e5 <unknown>\n#12 0x55795fae2012 <unknown>\n#13 0x55795fafa30e <unknown>\n#14 0x55795fae1de3 <unknown>\n#15 0x55795fab72dd <unknown>\n#16 0x55795fab834e <unknown>\n#17 0x55795fd173e4 <unknown>\n#18 0x55795fd1b3d7 <unknown>\n#19 0x55795fd25b20 <unknown>\n#20 0x55795fd1c023 <unknown>\n#21 0x55795fcea1aa <unknown>\n#22 0x55795fd406b8 <unknown>\n#23 0x55795fd40847 <unknown>\n#24 0x55795fd50243 <unknown>\n#25 0x7fc5bac90402 <unknown>\n\n",
  "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 27, in step_impl\n    context.driver.get(url)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_ADDRESS_UNREACHABLE\n  (Session info: headless chrome=114.0.5735.133)\nStacktrace:\n#0 0x55795fd574e3 <unknown>\n#1 0x55795fa86c76 <unknown>\n#2 0x55795fa7ec7f <unknown>\n#3 0x55795fa70ca2 <unknown>\n#4 0x55795fa72412 <unknown>\n#5 0x55795fa710ca <unknown>\n#6 0x55795fa70168 <unknown>\n#7 0x55795fa6ffa0 <unknown>\n#8 0x55795fa6e9bf <unknown>\n#9 0x55795fa6efed <unknown>\n#10 0x55795fa88b06 <unknown>\n#11 0x55795fafa9e5 <unknown>\n#12 0x55795fae2012 <unknown>\n#13 0x55795fafa30e <unknown>\n#14 0x55795fae1de3 <unknown>\n#15 0x55795fab72dd <unknown>\n#16 0x55795fab834e <unknown>\n#17 0x55795fd173e4 <unknown>\n#18 0x55795fd1b3d7 <unknown>\n#19 0x55795fd25b20 <unknown>\n#20 0x55795fd1c023 <unknown>\n#21 0x55795fcea1aa <unknown>\n#22 0x55795fd406b8 <unknown>\n#23 0x55795fd40847 <unknown>\n#24 0x55795fd50243 <unknown>\n#25 0x7fc5bac90402 <unknown>\n\n",
    "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 27, in step_impl\n    context.driver.get(url)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
    "steps" : [ {
      "name" : "Given The user is on the \"live\" site",
      "time" : {
        "start" : 1698836812968,
        "stop" : 1698836813147,
        "duration" : 179
      },
      "status" : "broken",
      "statusMessage" : "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_ADDRESS_UNREACHABLE\n  (Session info: headless chrome=114.0.5735.133)\nStacktrace:\n#0 0x55795fd574e3 <unknown>\n#1 0x55795fa86c76 <unknown>\n#2 0x55795fa7ec7f <unknown>\n#3 0x55795fa70ca2 <unknown>\n#4 0x55795fa72412 <unknown>\n#5 0x55795fa710ca <unknown>\n#6 0x55795fa70168 <unknown>\n#7 0x55795fa6ffa0 <unknown>\n#8 0x55795fa6e9bf <unknown>\n#9 0x55795fa6efed <unknown>\n#10 0x55795fa88b06 <unknown>\n#11 0x55795fafa9e5 <unknown>\n#12 0x55795fae2012 <unknown>\n#13 0x55795fafa30e <unknown>\n#14 0x55795fae1de3 <unknown>\n#15 0x55795fab72dd <unknown>\n#16 0x55795fab834e <unknown>\n#17 0x55795fd173e4 <unknown>\n#18 0x55795fd1b3d7 <unknown>\n#19 0x55795fd25b20 <unknown>\n#20 0x55795fd1c023 <unknown>\n#21 0x55795fcea1aa <unknown>\n#22 0x55795fd406b8 <unknown>\n#23 0x55795fd40847 <unknown>\n#24 0x55795fd50243 <unknown>\n#25 0x7fc5bac90402 <unknown>\n\n",
      "statusTrace" : "  File \"/usr/local/lib/python3.10/dist-packages/behave/model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"/usr/local/lib/python3.10/dist-packages/behave/matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"steps/PageRedirectionSteps.py\", line 27, in step_impl\n    context.driver.get(url)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 355, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py\", line 346, in execute\n    self.error_handler.check_response(response)\n  File \"/home/addweb/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n",
      "steps" : [ ],
      "attachments" : [ {
        "uid" : "952d360edacaed66",
        "name" : "Error Message",
        "source" : "952d360edacaed66.txt",
        "type" : "text/plain",
        "size" : 877
      }, {
        "uid" : "4840cf8fd56b0c0c",
        "name" : "Screenshot of https://www.voltactivedata.com/ Page",
        "source" : "4840cf8fd56b0c0c.png",
        "type" : "image/png",
        "size" : 7513
      } ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 2,
      "shouldDisplayMessage" : true,
      "hasContent" : true
    }, {
      "name" : "When The user hovers over the \"resources\" menu",
      "time" : {
        "start" : 1698836813202,
        "stop" : 1698836813202,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    }, {
      "name" : "And The user clicks on the \"documentation\" submenu link and verify the redirection \"documentation\" page",
      "time" : {
        "start" : 1698836813202,
        "stop" : 1698836813202,
        "duration" : 0
      },
      "status" : "skipped",
      "steps" : [ ],
      "attachments" : [ ],
      "parameters" : [ ],
      "stepsCount" : 0,
      "attachmentsCount" : 0,
      "shouldDisplayMessage" : false,
      "hasContent" : false
    } ],
    "attachments" : [ ],
    "parameters" : [ ],
    "stepsCount" : 3,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : false,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "severity",
    "value" : "normal"
  }, {
    "name" : "feature",
    "value" : "Test Redirection of Pages"
  }, {
    "name" : "framework",
    "value" : "behave"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "33c0d416f156efbb.json",
  "parameterValues" : [ ]
}